version: '3.8'
services:
  bot:
    build:
      context: .
      dockerfile: ./deployments/Dockerfile
    image: discordbot
    container_name: discordbot
    env_file:
      - .env
    volumes:
      - ./db_dir:/app/db
    restart: unless-stopped